services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/users_db
    depends_on:
      postgres:
        condition: service_healthy

  budgets:
    build:
      context: .
      dockerfile: ./budgets/Dockerfile
    ports:
      - "8001:8001"
